electron/trop

.gitignore
package.json
spec/index.test.js
src/backport/Probot.ts
src/backport/Queue.ts
src/backport/utils.ts
src/index.js
tsconfig.json

Allow for automatic pull request creation to backport fixes in `master` to other branches.

Backporting magic

---

.gitignore
spec/fixtures/issues.unlabeled.json
spec/fixtures/pull_request.unlabeled.json
spec/index.test.js
src/index.js

This PR removes cards from the project board when labels are removed
Todo:

Remove card on unlabel

---

spec/index.test.js
src/backport/Probot.ts
src/backport/utils.ts
src/index.js

Support pr's from forks, support multiple repos

---

src/index.js

Adds descriptive logging and cleans up a few things

Improve error logging and output

---

.dockerignore
Dockerfile
docker/build
docker/run
docker/stop
package.json
prod.sh
runner.Dockerfile
src/backport/commands.ts
src/backport/runner.ts
src/backport/utils.ts

run git logic in a sandboxed environment

---

src/index.js

Removing electron-specific things to make this more customizable

make bot more customizable

---

spec/fixtures/issue_comment.created.json
spec/fixtures/pull_request.closed.json
spec/index.test.js
src/index.js

Adding more specs

---

src/backport/runner.ts
src/backport/utils.ts

Use patch files from GitHub instead of cherry-picking commit SHA's

---

README.md

Is there a simpler way to make this transformation?

add origin story

---

package.json
src/backport/commands.ts
src/backport/runner.ts
src/backport/utils.ts

This PR takes steps to move `trop` from Sam's closet server in France to Heroku for robustness and maintainability. 
/cc @zeke @MarshallOfSound

feat: move trop to heroku

---

src/backport/utils.ts

This was causing some checks not to complete
cc @codebytere

fix: handle a file diff not having hunks

---

src/backport/utils.ts

fix: replace * with x when filtering branch names

---

src/backport/utils.ts

Sometimes people will open manual backports before the original pull request is merged; trop was previously looking just for the `needs-manual` label prefix but if the former event occurs then it will fail to update the label. This PR thus checks for the existence of `needs-manual` first and then falls back to `target` if it's not present.
Also extracts label adding and removing to helper functions.
cc @MarshallOfSound @BinaryMuse

fix: try to update manual if target label still exists

---

src/backport/utils.ts

fix: allow maintainers to modify trop PRs

---

docs/usage.md

The old usage file had a few old features we have since removed

chore: update usage

---

package.json
src/backport/runner.ts
src/backport/utils.ts
src/index.ts
yarn.lock

This PR also updates octokit to get a small fix

feat: support private repositories

---

.circleci/config.yml
.travis.yml
src/backport/__tests__/runner.spec.ts

This moves our CI config to CircleCI

build: move to circleci

---

src/backport/utils.ts

Fixes the following auth error:
```
{ HttpError: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","field":"fork_collab","message":"fork_collab Fork collab can't be granted by someone without permission"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

fix: revert maintainer_can_modify param

---

src/index.ts

`electron-bot` PRs should not have to follow backport requirements

fix: exclude electron-bot from the backport requirements so roller works

---

src/index.ts

Group logic for actions taken after trop's PRs are merged.
Also add logging to diagnose potential automatic branch deletion on merge.
cc @ckerr @MarshallOfSound

refactor: group pr.closed logic

---

package.json
spec/index.spec.ts
src/index.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/label-utils.ts

This reverts commit ed52afee8a11993d53128ee4426f6e1c5881e537.

revert: "refactor: use @octokit/rest@16 pagination (#113)"

---

src/enums.ts
src/index.ts
src/operations/backport-commits.ts
src/operations/backport-to-location.ts
src/operations/init-repo.ts
src/operations/setup-remotes.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/branch-util.ts
src/utils/env-util.ts
src/utils/label-utils.ts
src/utils/log-util.ts
src/utils/token-util.ts

Improve and streamline logging so that we can more easily diagnose and fix trop failures when they occur. Also fixes a handful of malformed jsdoc/tsdoc comments.

chore: improve and streamline logging

---

src/index.ts

Closes https://github.com/electron/trop/issues/139.
this one hurts 🤦‍♀

fix: manual backports not being updated

---

src/Queue.ts
src/index.ts
src/utils.ts
src/utils/label-utils.ts

Adds more verbose debugging to trop logs.
cc @jkleinsc

chore: add more verbose debugging

---

src/utils.ts

Allow pulling commits forward to master.
cc @ckerr @jkleinsc

fix: allow forward-ports to master

---

src/utils/branch-util.ts

Refs https://github.com/electron/electron/pull/23709#issuecomment-632341796.
Fix supported branch pattern.

fix: supported branch pattern

---

.prettierrc
package.json
spec/commands.spec.ts
spec/index.spec.ts
spec/operations.spec.ts
spec/queue.spec.ts
src/Queue.ts
src/constants.ts
src/index.ts
src/interfaces.ts
src/operations/backport-commits.ts
src/operations/backport-to-location.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/branch-util.ts
src/utils/checks-util.ts
src/utils/env-util.ts
src/utils/label-utils.ts
src/utils/log-util.ts
src/utils/token-util.ts
tslint.json

chore: lint with prettier

---

docs/usage.md
spec/index.spec.ts
src/constants.ts

Improve trop env var docs a bit.

docs: improve env var docs

---

src/operations/update-manual-backport.ts

Seen in error at https://github.com/electron/electron/pull/25146.

fix: PRChange typecheck

---

package.json

Add lint-staged 
cc @codebytere

build: add lint staged

---

src/operations/update-manual-backport.ts

Closes https://github.com/electron/trop/issues/180.

fix: label updates on manual backports

---

spec/index.spec.ts
src/index.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/170.

feat: better bookkeeping for nested backports

---

src/utils.ts

Follow up to https://github.com/electron/trop/commit/d548b37bd0edcdb6019e6a5b30397969c02692c4 - ensure that when a nested backport is opened that the `in-flight` label is correctly added to the original PR and not the intermediary PR.
cc @ckerr @MarshallOfSound

fix: properly label nested backport backports

---

src/interfaces.ts
src/operations/backport-commits.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/185.
Cherry pick only the merge commit instead of each individual commit.

feat: cherry-pick squash commit

---

src/utils.ts

Closes https://github.com/electron/trop/issues/192.
Fixes a bug introduced in https://github.com/electron/trop/commit/1648c2feac71d564d68f1f0b7956671e663c454d which caught errors throw during cherry-picking. The queue works such that in order to complete the check the cherry picks needed to throw an error and thus enter the `ErrorExecutor`, which wouldn't happen if we wrapped the code in `try/catch`. This fixes that error and makes it such that failed cherry-picks show up as failed checks correctly.

fix: check success on failed backports

---

src/utils.ts

Closes https://github.com/electron/trop/issues/194.

fix: label removal from original PR

---

src/index.ts

What it says. Refs https://github.com/electron/electron/pull/29023.

fix: prevent backporting to own base branch

---

spec/fixtures/backport_pull_request.opened.json
spec/fixtures/pull_request.opened.json
src/index.ts
src/utils.ts

This should support both 'master' and 'main' as default branches.

feat: support default branch named main

---

src/operations/backport-commits.ts

Fixes an issue introduced by #221.

fix: set-upstream does not take a value

---

config.yml
src/interfaces.ts
src/operations/backport-commits.ts
src/operations/init-repo.ts
src/utils.ts

I believe that this should result in the commits that trop pushes being signed 🤔 But honestly, no idea

refactor: use gitdata API to push tree information

---

src/constants.ts
src/interfaces.ts
src/operations/backport-commits.ts
src/utils.ts

As in title. Prevents others from effectively using trop.

chore: remove hardcoded Electron vars

---

docs/local-setup.md
package.json

chore: update references to repo URL

---

docs/usage.md

docs: fix relative link

---

src/utils/branch-util.ts

Refs https://github.com/electron/sudowoodo/pull/241
Refs https://github.com/electron/unreleased/pull/85

build: extend release versions for E22

---

src/utils.ts
src/utils/label-utils.ts
typings/ambient.d.ts

Closes https://github.com/electron/trop/issues/255.

fix: dangling target labels on intermediary PRs

---

src/operations/update-manual-backport.ts

Function doesn't return anything.

chore: fix return type comment

---

package.json
yarn.lock

build: bump smee-client

---

.github/workflows/semantic.yml

ci: bump action-semantic-pull-request version

---

src/utils.ts

The issue trying to be resolved by #283 is still happening, but no errors in the logs. I think this might be it. 🤷

fix: await check update
