package.json
src/backport/utils.ts
src/index.js

Also:
* Sanitize branch name (colons in branches is not a thing apparently)
* Change initial check/out procedure, don't know why we were checking out `fork/target`

Add support for manual triggering of bot

---

src/index.js

Turns out singular issues are `/issues/<issue_number>` but individual pull requests are `/pull/<pr_number>` instead of `/pulls/<pr_number>`
Fixes cards not being removed from project columns on the `issues.unlabeled` webhook.

fix pull to issue conversion

---

src/index.js

Now stops at newlines. Fixes #28.

Fix backport-to branchname regex

---

README.md

Migrate travis builds to the `electron` [org](https://travis-ci.org/electron/trop) and update badge to reflect that.
/cc @ckerr @MarshallOfSound

Fix travis build status badge

---

package.json
src/backport/utils.ts

This PR makes trop's generated PR titles semantic for changelog purposes.
/cc @MarshallOfSound @ckerr @jkleinsc

fix: make backport PR titles semantic

---

spec/fixtures/issue_comment_backport_to_multiple.created.json
spec/index.test.js
src/backport/utils.ts
src/index.js

This PR allows for multiple PRs to be triggered in a single comment of the following format:
`/trop run backport-to 3-0-x,2-0-x`, where the target branches are comma-separated with no space. 
Todo:
/cc @MarshallOfSound @ckerr

feat: allow triggering multiple backports in same comment

---

src/backport/utils.ts

Resolves https://github.com/electron/trop/issues/41.
This PR also checks a given PR body for release notes and adds them to the backport PR body, such that trop's PRs will comply with the new `release-notes` check. 

feat: add PR release notes to backport PR body

---

src/backport/utils.ts

Since backport failures to release branches now show in the list of build checks, it's redundant for the bot to show a standalone comment indicating the same.

fix: no longer show failures in PR comments

---

src/backport/utils.ts

Resolves an issue whereby `Notes: no-notes` was being erroneously appended to generated PR bodies that had actual release notes.
See: https://github.com/electron/electron/pull/14823 and its associated backports to `3-0-x`/`2-0-x`

fix: incorrect no-notes being appended

---

src/backport/utils.ts

Allow backporting of multi-line release notes in concert with https://github.com/electron/clerk/pull/16.

feat: allow multiline release notes

---

src/backport/utils.ts

When backports fail, Trop once again will post an explicit comment to that effect.
/cc @alexeykuzmin

fix: add explicit bp error comment

---

src/backport/utils.ts

At the moment it's impossible to sort PRs by their target branch, so this PR enables trop to tag backport PRs with labels corresponding to the target branch (one of `['4-0-x', '3-0-x', '2-0-x', '1-8-x']`, which i've added as labels on `e/e`) so that they're more discoverable.
/cc @ckerr @MarshallOfSound

feat: label backport PRs with target branch

---

src/backport/Probot.d.ts
src/backport/utils.ts
src/index.ts

Resolves https://github.com/electron/trop/issues/44.
This PR allows for trop PRs to now be marked `in-flight/4-0-x` when they are opened, and only marked `merged/4-0-x` when the backport PRs themselves have been merged.

feat: add concept of in-flight

---

src/backport/utils.ts

Normally this means we send invalid annotations, so let's just send a
failure without them.
E.g. https://github.com/electron/electron/pull/15541

fix: try mark as failure without annotations when the GitHub API fails

---

src/backport/utils.ts

Improve regex used to filter PR titles for generated trop branch names.
/cc @nornagon @MarshallOfSound

fix: safer regex filtering for branch names

---

src/backport/utils.ts

Resolves https://github.com/electron/trop/issues/68.
Fixes an issue (see: [this PR](https://github.com/electron/electron/pull/15845)) whereby backport PRs triggered manually were calling `backportToBranch`, which was erroneously applying the `merged` label instead of the `in-flight` label.
/cc @ckerr

fix: correctly mark manual backports in-flight

---

src/index.ts

Prior to this, trop would fail silently when unauthorized users attempted to trigger comment-based `trop` backports. This explicitly lets those users know that they are not allowed to perform backports so that we don't think trop is failing for a more systemic reason.
/cc @BinaryMuse @ckerr

feat: error on unauthorized users

---

.travis.yml
package.json
src/backport/utils.ts
src/index.ts
yarn.lock

What it says on the tin. 
Updates to latest `@octokit/rest` so that we're using methods that match the latest docs.
/cc @BinaryMuse

feat: update to latest @octokit/rest

---

.github/CODEOWNERS

Update primary codeownership of trop to `@electron/wg-releases`, as it fall under one of their primary Associated Repositories.

chore: add wg-releases codeownership

---

src/backport/runner.ts

Setting `GITHUB_FORK_USER_CLONE_LOGIN` to your fork user's username will use that user's creds to clone the source repo.
This allows trop to work on private github repositories

feat: support authenticated clones

---

src/backport/utils.ts

Trop now adds `backport` and `$TARGET_BRANCH` labels to each PR so imo there's no longer a need to clutter the title with duplicate info.

fix: don't label PR title with target branch

---

src/backport/__tests__/commands.spec.ts
src/backport/commands.ts
src/backport/constants.ts
src/backport/runner.ts
src/backport/utils.ts
src/constants.ts
src/enums.ts
src/index.ts
src/interfaces.ts

A first step in a trop refactor, which involves abstracting out trop's constants, enums, and interfaces in order to more clearly reason about their uses and locations.

refactor: pull out constants, interfaces and enums

---

docs/manual-backports.md
src/backport/Probot.d.ts
src/backport/__tests__/fixtures/backport_pull_request.opened.json
src/backport/__tests__/index.spec.ts
src/backport/utils.ts
src/index.ts

When a PR is raised against a non-master branch Trop will try to figure out which PR it is "backporting".  If it can't determine it Trop will mark that PR as "failed" with a GitHub Check.
This ensures that no change can land in a release branch without having a corresponding commit / PR in master.  In cases where this must be overridden an Admin can bypass the merge check.
_Side Note_
This PR also fixes a few label creation / deletion bugs I found in the process of testing this PR.
See [this check](https://github.com/MarshallOfSound/electron/pull/78/checks?check_run_id=63908511) for an example of an invalid backport failed check.

feat: add a GitHub check that prevents non-master non-backports

---

src/backport/__tests__/runner.spec.ts
src/backport/utils.ts
src/index.ts
src/operations/task-runner.ts
src/utils/label-utils.ts

This PR begins to organize methods in a similar fashion to Sudowoodo, by organizing operations into a bespoke operations folder and a utils folder so that everything isn't crammed into `utils.ts`

refactor: start moving tasks to operations dir

---

src/backport/utils.ts

We want to leave the `target/5-0-x` label on PRs even if the check "fails" so that it will track manual backports correctly.  In order to avoid the PR appearing like it "failed" this check has been modified to be a neutral check.

chore: change a failed BP to be a neutral check

---

app.json
docs/.example.env
docs/local-setup.md
src/backport/__tests__/index.spec.ts
src/backport/__tests__/operations.spec.ts
src/backport/token.ts
src/backport/utils.ts
src/index.ts
src/operations/backport-commits.ts
src/operations/init-repo.ts

This removes the need for the fork user hack when making backports.  We now push all backports to `trop/*` branches on the _actual_ repository.  This means that PRs, commits, branches, everything are pushed and owned by the bot.
This is a required chunk of work to move towards actionification and makes the Private Repository workflow _wayyyyy_ better.  It would allow us to put `trop` in its current state on the GitHub Marketplace as others could just install it and it would work on any repository (private or public)

feat: remove need for fork user and fork token

---

src/index.ts

Allows us to label backport PRs as fasttrack to bypass the Valid Backport check

feat: allow fasttrack backports

---

src/index.ts

`trop[bot]` opens backport PRs and thus needs to be a fast-track user. Caused the following [fail](https://github.com/electron/electron/pull/17909).

fix: trop[bot] needs to be a fast-track user

---

src/backport/__tests__/fixtures/backport_pull_request.closed.bot.json
src/backport/__tests__/index.spec.ts
src/constants.ts
src/index.ts

Since trop no longer opens PRs from a fork, there are now dangling branches left when its PRs are merged. This PR thus enables trop to delete its own branches when they're merged.

feat: enable trop to delete its own branches when they're merged

---

src/backport/utils.ts
src/index.ts
src/utils/label-utils.ts

We don't use Probot's configuration file for anything to do with label prefixing, so we can simplify this code a bit by removing the unnecessary helper method.

chore: remove unused config file for label prefixes

---

src/backport/utils.ts
src/index.ts
src/utils/label-utils.ts

Fixes https://github.com/electron/trop/issues/101.
A check was added to ensure that the PR instigating had the label in question for removal, but when backport PRs are merged the label in question needs to exist on the _original_ PR and so this check would incorrectly fail. Thus we also should pass the PR number to check against.
We should also be updating labels on manual backport merges, so I've also added that here.

fix: duplicate issue comments for status changes

---

src/backport/utils.ts
src/index.ts

Fixes https://github.com/electron/trop/issues/100.
Correctly pass the old backport number to check for the `needs-manual` label as well as more tightly scope when `updateManualBackport` is called to PRs being opened and closed.

fix: double commenting on manual backport open

---

src/backport/__tests__/index.spec.ts
src/constants.ts
src/index.ts
src/utils/env-utils.ts

Closes https://github.com/electron/trop/issues/105.
Extracts bot names (in our case `trop[bot]` and `electron-bot`) to environment variables to increase trop's extensibility. Check env vars when they are used to ensure they've been appropriately set, or throw an error to let users know they need to set them.

feat: allow consumers to set bot names in env

---

src/index.ts

Fixes https://github.com/electron/trop/issues/107.
We account for both links and PR numbers when searching a PR body to look for valid backports, but did not take into account that this changes which capture group is populated with the valid number. 
This PR adds a truthy check to the first capture group (a PR number), and if it's `undefined` uses the second capture group's value, which must then be correct because the user pasted a link.

fix: invalid backports when links are used

---

src/backport/__tests__/index.spec.ts
src/backport/utils.ts
src/enums.ts
src/index.ts
src/operations/backport-to-location.ts

Continues to split out the utils file into operations. This PR specifically moves the backport to branch and backport to label actions into their own operations file.

refactor: move backport to branch/label to ops

---

jest.config.js
src/backport/__tests__/index.spec.ts

This PR cleans up our use of Jest function mocks so that we don't need to define the same object property in each test.
cc @MarshallOfSound @ckerr

test: clean up spec utility fn mocks

---

package.json
src/backport/__tests__/fixtures/backport_pull_request.closed.bot.json
src/backport/__tests__/fixtures/backport_pull_request.closed.json
src/backport/__tests__/fixtures/backport_pull_request.opened.json
src/backport/__tests__/fixtures/issue_comment_backport.created.json
src/backport/__tests__/fixtures/issue_comment_backport_to.created.json
src/backport/__tests__/fixtures/issue_comment_backport_to_multiple.created.json
src/backport/__tests__/fixtures/pull_request.closed.json
src/backport/__tests__/index.spec.ts
src/backport/utils.ts
src/index.ts

Does what it says on the tin.
This is a prerequisite for using pagination when pulling down PRs, since v7 doesn't use a recent enough version of `@octokit/rest`.
cc @MarshallOfSound @ckerr

chore: update probot to v9

---

package.json
src/backport/__tests__/index.spec.ts
src/backport/utils.ts
src/index.ts
src/operations/update-manual-backport.ts
src/utils/label-utils.ts

Follow-up to https://github.com/electron/trop/pull/112.
We previously had an issue wherein trop would stop functioning properly after 100 pull requests owing to lack of pagination abilities.
The `.paginate` function was added in `@octokit/rest@16`, which was only rolled into `probot@9`.
Now that we have this in `master`, i've refactored our `octokit` calls to take advantage of it and thereby ameliorate the PR cap issue.
cc @electron/wg-releases @MarshallOfSound

refactor: use @octokit/rest@16 pagination

---

src/operations/update-manual-backport.ts

Closes https://github.com/electron/trop/issues/119.
Add labels for the backport and target branch to the manual backport if the maintainer forgot to do so themselves.

feat: pass backport and target branch to manual backports

---

src/operations/update-manual-backport.ts

Closes https://github.com/electron/trop/issues/121.
Changes trop's manual backport comment copy from:
> A maintainer has manually backported this PR to "BRANCH", please check out #12345
to 
> @codebytere has manually backported this PR to "BRANCH", please check out #12345

feat: specify manual backport opener in comment

---

src/index.ts

Fixes the issue we've been seeing recently where Trop wouldn't properly label backports to `8-x-y`. Our regex was checking for the old pattern only so this updates it to account for both.
Will now match both `7-0-x` & `8-x-y` formats.

fix: update regex for new minor pattern

---

src/index.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/label-utils.ts

These were all deprecated per papertrail, so update them to the newer versions.
Example:
```
Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
```
cc @ckerr @MarshallOfSound @jkleinsc

chore: update deprecated number properties

---

src/index.ts

Refs https://github.com/electron/electron/pull/21773.
It's not uncommon that a PR would need to directly target a release branch, and then potentially be backported to other PRs from that initial PR. This PR thus allows PRs to be marked valid as long as the PR they are backporting targeted a valid release branch.
cc @MarshallOfSound @jkleinsc @ckerr

feat: allow backporting from PRs to release branches

---

src/constants.ts
src/index.ts

Closes https://github.com/electron/trop/issues/135.
Previously trop assumed that any branch with a parent that isn't master is a backport, which might not be the case since many dev flows break work into several branches and PR-🚂 them into one another.
This PR adds a new label that allows skipping that validity check. It defaults to `backport-check-skip`, but can be set via an environment variable `SKIP_CHECK_LABEL`. If this label is appended to a PR, the associated check for backport validity will be marked neutral.
cc @tommoor @MarshallOfSound @jkleinsc

feat: allow skipping backport validity check

---

src/index.ts

Fixes an issue where when new commits were added to an existing branch, the `SKIP_CHECK_LABEL` label would not take effect. We only run this check on:
```
[
'pull_request.opened',
'pull_request.edited',
'pull_request.synchronize',
'pull_request.labeled',
'pull_request.unlabeled',
]
```
anyway, so it's fine to just run this and short-circuit potentially every time.
cc @jkleinsc @ckerr @MarshallOfSound @tommoor

fix: always check for skip label on pr change

---

src/index.ts

Fix for the struggle [seen here](https://github.com/electron/electron/pull/23153).
When manual backports are merged, it looks for the `x-y-z` label on the manual backport PR, and then updates the original PR with `merged/x-y-x`. However, if someone tries to tag a manual backport _itself_ for backports, the `target/x-y-z` labels also get caught up in the regex, and then are appended unexpectedly to the original PR. This stops that from happening by ensuring that no labels are caught which are not _only_ `x-y-z`.
In an ideal world, it adds `needs-manual` to the original PR, but i'll get that as a follow-up.

fix: ignore target labels on manual backports

---

src/index.ts

Allow backports that combine 1 or more PRs into one, e.g. https://github.com/electron/electron/pull/23299.
Tested to ensure that running the new patterns on:
```text
Backport of #23194
Backport of #23235
See those PRs for details.
Notes: no-notes
```
Produces: `[ 23194, 23235 ]`

feat: allow combination backports

---

src/constants.ts
src/index.ts
src/utils.ts
src/utils/branch-util.ts

Refs https://github.com/electron/trop/pull/148.
Ensure that when combination backports are merged, the `in-flight/<branch>` labels are updated to  `merged/<branch>` for all initial PRs in the combo.

fix: update labels properly on combo backport merges

---

src/enums.ts
src/index.ts
src/utils/checks-util.ts

Fixes an issue where valid backports would show up as endlessly queued:
owing to a condition oversight in fast-track PRs. This also refactors out the check update code to make it a little more organized.

fix: endless queued Valid Backport Check

---

src/utils/branch-util.ts

`10-x-y < 9-x-y` in string comparisons.

fix: sort branches by number not by string

---

src/constants.ts
src/utils.ts

Automatically label semver-minor PRs being backported with the `backport/requested` label.

feat: automatically label semver-minor pr backports

---

src/enums.ts
src/index.ts
src/operations/update-manual-backport.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/140.
Previously, when manual backports were closed but not merged, the `in-flight` label would never be removed. This ensures that it is now removed when manual backports are closed with unmerged commits.

fix: remove in-flight label when PRs are closed

---

src/constants.ts
src/utils.ts

Right now, trop only requests review from the PR author if they have merge rights, and no one otherwise. Now, request @electron/wg-releases review for _all_ backports,  and if the PR author has write access, also request their review.

feat: fallback to default team for bp approval

---

spec/fixtures/backport_pull_request.closed.bot.json
spec/index.spec.ts
src/index.ts
src/operations/backport-to-location.ts

Delete correct branch when a trop PR is merged.
Error seen [here](https://my.papertrailapp.com/systems/electron-trop/events?focus=1254944350363930706&selected=1254944350363930706) - we were previously trying to delete the base branch e.g `10-x-y` instead of the head branch e.g `backport-to-10-x-y`.

fix: delete proper ref

---

spec/index.spec.ts
src/index.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/162
Previously when trop backport was closed, trop would keep the in-flight label rather than removing it. This was occurring because we were lacking logic to handle non-manual backport being closed with unmerged commits.
cc @codebytere

fix: labels when trop PR closed unmerged

---

spec/fixtures/backport_pull_request.closed.json
spec/fixtures/backport_pull_request.merged.bot.json
spec/fixtures/backport_pull_request.merged.json
spec/index.spec.ts

Improve labeling specs for trop. Check correct paths are taken for PRs closed with unmerged commit vs merged.
cc @mlaurencin @MarshallOfSound

test: improve trop labeling specs

---

spec/fixtures/issue_comment_backport_to_multiple_spaces.created.json
spec/index.spec.ts
src/index.ts

Refs https://github.com/electron/electron/pull/26586.
Previously, backport trigger comments needed to be:
```
/trop run backport-to 12-x-y,11-x-y,10-x-y
```
and if the branches has spaces between them the first branch would work but the latter two would silently fail. This makes the process more flexible by also allowing space-separated branches:
```
/trop run backport-to 12-x-y, 11-x-y, 10-x-y
```

fix: make backport-to more flexible

---

src/operations/update-manual-backport.ts
src/utils.ts

As in title, now these labels are required our bots should automatically add these labels where appropriate.

feat: copy semver/* labels from the original PR to the backported PR

---

spec/index.spec.ts
src/index.ts
src/interfaces.ts
src/utils.ts

It doesn't make a lot of sense to maintain a [brittle backport list](https://github.com/electron/electron/blob/master/.github/config.yml#L30-L41) that's entirely divorced from governance. Instead, we should allow all users who are members of teams with write access to interact with trop.

feat: allow users with write access to backport

---

src/index.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/174.
If a pr is closed with unmerged commits and it's a PR to master (e.g. not a backport) then trop should handle label updates and nothing else.

fix: trop backporting on close unmerged

---

src/constants.ts
src/index.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/label-utils.ts

Closes https://github.com/electron/trop/issues/176.
Cleans up some labeling logic and fixes an issue with manual backports not having semver labels applied.

fix: label manual backports with semver labels

---

src/operations/update-manual-backport.ts
src/utils.ts

Like automatic backports, if a PR is semver-minor a backport should be requested for the Releases WG.

fix: label semver-minor backports with requested

---

src/utils.ts

Fixes issue seen https://github.com/electron/electron/pull/27224 introduced by https://github.com/electron/trop/commit/55615207c16c69abaa89b0493ed42703c675a110.

fix: backport label applied to backport not original

---

src/utils.ts

Seen here: https://github.com/electron/electron/pull/28150
When both individual cherry-picking and squash commit picking failed we were early-returning which prevented the GitHub Check update from finishing and reflecting the failure.

fix: check stall when both pick approaches failed

---

src/operations/init-repo.ts

No need to explicitly checkout the default branch, it should be automatically
checked out by `git pull`.

chore: skip explicit checkout of master

---

spec/index.spec.ts
src/operations/backport-commits.ts

Previously we re-used a potentially dirty cherry-pick branch across cherry-pick strategies.  This ensures that if the branch exists we delete it before continuing.

fix: ensure the temporary branch is in a clean state before backporting

---

src/operations/backport-commits.ts

We should delete the local branch even if it contains unmerged commits, that's kinda the whole point.  This also contains:
* Two logging changes to make issues like this easier to debug
* A change to abort any in-progress patch because `git am` leaves a hanging rebase behind

fix: branch deletion now works

---

src/index.ts
src/utils.ts

Fix a couple of missing `await` calls in the codebase that I spotted via https://lgtm.com/projects/g/electron/trop/?mode=list
```diff
diff --git a/src/utils.ts b/src/utils.ts
index 92e767b..324751b 100644
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -56,7 +56,7 @@ export const labelClosedPR = async (
if (change === PRChange.CLOSE) {
const targetLabel = PRStatus.TARGET + targetBranch;
-    if (labelUtils.labelExistsOnPR(context, pr.number, targetLabel)) {
+    if (await labelUtils.labelExistsOnPR(context, pr.number, targetLabel)) {
await labelUtils.removeLabel(context, pr.number, targetLabel);
}
}
```
This one changed the code to always try to remove a label whether or not it existed. TBH it might be better to just remove this test altogether, since there's no downside (that I know of) to …

fix: add missing 'await' prefix when calling async

---

src/utils.ts

Fixes issue seen here: https://github.com/electron/electron/pull/29729
A manual backport was triggered for an older PR _from a backport_ which could not be automatically backported from the PR to `main`. Our logic correctly added the in-flight label to the original but didn't account for the `needs-manual` label being present.

fix: manual/target label removal

---

.circleci/config.yml
.gitignore

Previously failing:
> node-fetch@3.1.1: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "10.15.3
See https://github.com/electron/trop/pull/212

ci: update Node.js Docker image

---

src/constants.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/label-utils.ts

Fix an issue where multiple semver labels could incorrectly be applied to a single PR.
See https://github.com/electron/electron/pull/33292.

fix: backports with conflicting semver-labels

---

src/index.ts

This allows us to make it a required check, if it isn't always made then it won't be present for some PRs and will block incorrectly.

fix: always make Valid Checkport check

---

docs/manual-backports.md
docs/usage.md
src/utils.ts
src/utils/checks-util.ts

This PR switches `trop` from CircleCI to GitHub Actions as well as updates references to prepare for a switch from `master` to `main`.

chore: switch from master to main

---

src/constants.ts
src/index.ts

This PR bumps the number of supported versions from 5 back to 4 as the [extended release timeline](https://www.electronjs.org/blog/8-week-cadence#2021-plan-for-releases) comes to a close.
NOTE: Please do not merge until after the last 15-x-y and 16-x-y releases have been cut on Tuesday, May 24th

chore: decrease number of supported branches

---

README.md

Was still pointing at Travis CI, instead of CircleCI

docs: update status badge

---

package.json
yarn.lock

This makes #236 compile properly.
* `@types/node` is updated to Node 18 LTS. The latest version of `simple-git` includes `AbortSignal` symbol somewhere in its TypeScript definitions, which was only available starting in Node 15 ([AbortSignal on MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)).
* `@types/express-serve-static-core` had a bug that required a patch version upgrade in `yarn.lock` (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46639#issuecomment-858857876)
* Removed the top-level `@types/express` dependency it was different from the one resolved through Probot.

chore: fix simple-git dep update

---

docs/.example.config
docs/usage.md

As far as I can tell, trop no longer uses `.github/config.yml` at all, and instead checks authorized users directly, so this example config is not needed.
https://github.com/electron/trop/blob/f4884ec06b0520ffb14d32bef4c3e8ee3b69688f/src/utils.ts#L252-L263

docs: remove outdated example config

---

src/index.ts

Fixes an issue where the valid backport information check will hang in the pending state for a merged PR with only `needs-manual-bp/x-y-z` labels.

fix: needs manual backport label counts as valid backport info

---

src/operations/backport-commits.ts

If the file being patched has CRLF line endings, `git am` will fail to apply an otherwise good patch. That's what causes the backport to `24-x-y` on https://github.com/electron/electron/pull/37603 to fail.
This change refs [`script/lib/git.py`](https://github.com/electron/electron/blob/42e7cd9b3f3e16d07f162716b4f1346e32004aec/script/lib/git.py#L59-L62) in `e/e` where the `--keep-cr` option is enabled by default with the usage of `git am` for applying patches there, for this same reason:
```python
args += ['--keep-cr']
```
For reference, here are the logs for the failed backport on that PR:
<details>
```
backportImpl: Fetching squash commit details
backportImpl: Got squash commit details
backportImpl: Checking out target: "target_repo/24-x-y" to temp: …
```

fix: use --keep-cr option for git am

---

.eslintrc.json
package.json
src/index.ts
src/types.ts
src/utils.ts
yarn.lock

Per [project](https://www.npmjs.com/package/tslint):
> TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

build: switch to ESLint from TSLint

---

src/utils/branch-util.ts

This PR removes extended support for Electron 22.
Reverts commit 61389182216f72c45ff094a6f92c6d0741c56511.

build: revert extended release versions for E22

---

CONTRIBUTING.md

Follow-up to #266, didn't notice this file linked directly to the removed file. Updates it to match the blurb in other `CONTRIBUTING.md` files in the org.

docs: fix CoC link in contributing.md

---

spec/index.spec.ts
src/index.ts
src/operations/update-manual-backport.ts
src/utils.ts

Not sure what happened with de0120fec24c093d519310624a8bee69d975149a, but the output is not the format that prettier on a clean checkout is expecting. Ran `yarn prettier:format` on a clean checkout to fix it.

build: run prettier to fix lint

---

docs/usage.md
spec/branch-util.spec.ts
spec/index.spec.ts
src/constants.ts
src/index.ts
src/utils/branch-util.ts
src/utils/checks-util.ts

This improves the existing support for the `SUPPORTED_BRANCH_PATTERN`
configuration variable.
1. The configured pattern is now consistently used everywhere we check
branches. Previously there were a few places that hardcoded a check for
Electron's branch pattern.
2. We now use the regex's groups to determine branch ordering, instead of
always splitting by `-`.
3. Numeric groups are sorted numerically, otherwise groups are sorted
lexically. This allows non-numeric branch patterns.
4. Documented the environment variables that control this behavior.
5. Changed a couple of error messages that referenced the default branch
pattern to be more generic.
6. Added some tests for branch matching.

feat: make custom branch patterns more useful

---

docs/manual-backports.md
src/utils.ts

Problem:
- Trop sometimes fails to automatically backport where there are merge conflicts. Instructions on how to manually backport is not easy to find. 
This PR:

chore: update manual backport readme and trop comment with `e backport` command

---

spec/fixtures/backport_pull_request.closed.json
spec/fixtures/backport_pull_request.merged.json
spec/fixtures/backport_pull_request.opened.json
spec/index.spec.ts
spec/operations.spec.ts
spec/queue.spec.ts
src/operations/update-manual-backport.ts
src/utils.ts

fix: add default reviewers to manual backports

---

src/utils.ts

fix: add team_reviewers to requestReviewers

---

src/operations/init-repo.ts

Follow-up to #275 where I gave a bad suggestion to remove this code - turns out it's required for running `git am` even if we're making the actual commit via the GitHub API.
Not sure if `await git.addConfig('commit.gpgsign', 'false');` also needs to be restored, will watch the logs and do another PR if that's necessary.

fix: restore setting user in git config

---

spec/operations.spec.ts
spec/utils.spec.ts
src/utils.ts

refactor: add try catch to reviewer

---

src/index.ts
src/operations/backport-to-location.ts
src/utils.ts

Seeing what looks like a race condition where for some window of time after creating a check run, subsequent requests to get said check run don't find it. This can lead to a forever queued backportable check. This was likely exacerbated by one of the changes in #253.

fix: race condition with check runs

---

src/index.ts
src/operations/backport-to-location.ts
src/utils.ts

Trying to confirm what's causing backportable checks to get stuck in `queued` state.

chore: add some logs for debugging

---

src/index.ts
src/operations/backport-to-location.ts
src/utils.ts
src/utils/checks-util.ts

Partially reverts #283.
Applying multiple labels to a PR at the same time can cause multiple webhook events to trigger multiple runs of the same backportable checks in trop. [The queue ensures there's only one](https://github.com/electron/trop/blob/48fa8b4232ce8c29836e80c7e4e0c64251566752/src/Queue.ts#L24) in-progress at a time, but the existing code creates/updates check runs before entering the queue. Creating a new check run with the same name simply overwrites any existing ones. This situation lead to various race conditions where check runs are modified in ways which lead to an inconsistent result displayed on GitHub. Resolution is simply to only modify the check runs inside the queue (effectively a critical section) to guarantee no one else is touching them.

fix: only modify backportable checks inside queue

---

spec/index.spec.ts

This PR adds tests for updateBackportValidityCheck to expand coverage of index.ts.

test: add test for updateBackportValidityCheck

---

src/index.ts

Fixes an issue where a trop PR comment like:
```
\trop run backport-to 32-x-y,32-x-y,30-x-y
```
would incorrectly produce two PRs to 32.

fix: prevent accidental branch backport duplication

---

app.json

[Heroku stopped including Git at runtime](https://devcenter.heroku.com/articles/heroku-24-stack) with `heroku-24`, which is kind of a problem for trop since it uses Git at runtime. 😄 This should buy us some time to get a more proper fix in place.

build: pin to heroku-22 stack

---

src/index.ts

Secondary to https://github.com/electron/trop/pull/300
Cleans up some comment-initiated backport logic

refactor: improve branch support logic

---

Aptfile
app.json
src/constants.ts
src/index.ts
src/utils.ts

Closes https://github.com/electron/trop/issues/303.

fix: ensure git found on trop runner

---

package.json
spec/queue.spec.ts
yarn.lock

No need to use `sinon` here, we can just use Jest mocks.

test: remove sinon usage

---

src/utils.ts

Closes https://github.com/electron/trop/issues/297.
Ensures that when a backport PR is opened manually, and then target labels are put on that, that the resultant bookkeeping is performed correctly.
1. PR 123 is opened and set to target branches x, y, and z 
2. PR 123 is reviewed and merged
3. Trop opens a backport to z, but can't backport to x and y
4. A maintainer opens a manual backport to y and adds a target to x, which shows it will be clean
5. When the manual backport to y is merged, trop opens a backport from y to x
6. When the auto-backport to x is merged, the original PR 123 should have its label updated to reflect that and the target label should be removed from the PR to y.

fix: remove needs-manual label from original PR

---

package.json
src/operations/backport-commits.ts
yarn.lock

You have to make blobs and attach them via `sha` reference if the contents is not a utf8 string.
Fixes #310

fix: support non-utf8 files in backports

---

src/operations/backport-commits.ts

It's not necessary to use `<const>`/`as const` here because the implicit type is already correct. Since the code is directly returning the objects as the value for a typed key, type inference works correctly and the string literals are correctly typed as literals.

chore: remove unnecessary type assertions

---

yarn.lock

Clears a security warning regarding `send`.

build: bump express to clear audit

---

src/operations/backport-commits.ts
src/operations/backport-to-location.ts
src/operations/init-repo.ts
src/operations/setup-remotes.ts
src/operations/update-manual-backport.ts
src/utils/branch-util.ts
src/utils/env-util.ts
src/utils/log-util.ts
src/utils/token-util.ts

Most of the "conversion" here is simply deleting `@param` and `@returns` which are only types, since they're redundant to the TS types, sometimes wrong, and TSDoc doesn't include types for obvious reasons.

chore: convert JSDoc comments to TSDoc

---

spec/index.spec.ts
spec/operations.spec.ts
spec/utils.spec.ts
src/Queue.ts
src/operations/update-manual-backport.ts
src/utils.ts
src/utils/label-utils.ts
src/utils/log-util.ts

Just some cleanup of the typings in this codebase.
* Use `jest.mocked` for better typing
* `mockReturnValue(Promise.resolve(...))` -> `mockResolvedValue(...)`
* Improve typing and remove most `as any` and `: any` types

chore: improve typings and test mocks

---

package.json
yarn.lock

`config-yml` was removed as a dependency in #259, so these resolutions are unnecessary now.

build: remove unused resolutions

---

package.json
spec/operations.spec.ts
src/operations/backport-commits.ts
src/operations/init-repo.ts
src/utils.ts
yarn.lock

Not necessary so trim this dependency.

refactor: remove fs-extra usage

---

package.json
src/utils.ts
yarn.lock

This reverts commit 56744cf13894381ae86cb1f39f21a0daf9778a0b.
Ref https://github.com/electron/trop/pull/317
We still need node-fetch for now - we explicitly delete global fetch to support proxies via global-agent:
https://github.com/electron/trop/blob/439152f4a57b77d83d67e8ea6dc3c2dd6e8c8b4d/src/index.ts#L40-L41
And without this trop fails with `fetch is not defined`

revert: drop node-fetch dependency

---

.husky/pre-commit
package.json
yarn.lock

Deferring updating ESLint as the migration from v8 to v9 is more involved.

build: update most dev dependencies

---

spec/fixtures/backport_pull_request.labeled.json
spec/fixtures/backport_pull_request.unlabeled.json
spec/index.spec.ts
src/constants.ts
src/index.ts
src/utils/checks-util.ts

There's currently nothing blocking PRs with `backport/requested 🗳` from being merged before they've been formally approved. This adds a check which can be set as a required check for merging on `e/e`, same as how trop's "Valid Backport" check is a required check.
The check is dead simple, it's marked as queued when the `backport/requested 🗳` label is present (so that it can block merging), otherwise it's marked as success (if no `backport/*` labels are present or `backport/approved ✅` is present).

feat: enforce backport approval with checks

---

spec/fixtures/backport_pull_request.closed.bot.json
spec/fixtures/backport_pull_request.closed.json
spec/fixtures/backport_pull_request.labeled.json
spec/fixtures/backport_pull_request.merged.bot.json
spec/fixtures/backport_pull_request.merged.json
spec/fixtures/backport_pull_request.opened.json
spec/fixtures/backport_pull_request.unlabeled.json
spec/fixtures/pull_request.closed.json
spec/fixtures/pull_request.opened.json
spec/index.spec.ts

The test fixtures for backport PRs were not quite right as they didn't have their `base.ref` set to a non-`main` branch. Updates the fixtures to be accurate and then some minor tweaks to the tests to get them working again. Also added a missing `pull_request.number` field on some of the fixtures - note that in the webhook event payload `number` is indeed both a top-level field and duplicated inside `pull_request`.
Marks the tests I added in #336 as skipped because I whiffed the implementation in that PR but didn't notice at the time because the tests passed due to the incorrect test fixtures. Fixing them cause the tests to fail, so I'm going to skip them for now and they'll be fixed in a follow-up PR that fixes the feat added in #336.

test: fix up backport tests

---

spec/fixtures/pull_request.labeled.json
spec/fixtures/pull_request.unlabeled.json
spec/index.spec.ts
src/index.ts

Follow-up to #336 with a more correct implementation not that test fixtures are updated. 😅 Discussed with @jkleinsc that we can add the required check on `e/e` on only release branches, so that's what the fixed implementation does.

fix: move backport approval enforcement to correct code path
